apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yaml --out ./meinfest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: quizapp
  name: quizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quizapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yaml --out ./meinfest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: quizapp
    spec:
      containers:
        - image: sriramravi477/quiz-app:54
          name: quizapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
