apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yaml --out ./meinfest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: quizapp
  name: quizapp
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006
  type: LoadBalancer
  selector:
    io.kompose.service: quizapp
